"""
Event dataclasses and spec functions for all major DOM event types, following MDN documentation.

This module provides Python representations of the corresponding DOM events and their data objects, clustered by event type.

Exports all event dataclasses and spec functions from submodules.
"""

from .animation_transition_events import (
    AnimationEndEvent,
    AnimationEvent,
    AnimationIterationEvent,
    AnimationStartEvent,
    TransitionEvent,
    WebGLContextEvent,
    animation_end_event_spec,
    animation_event_spec,
    animation_iteration_event_spec,
    animation_start_event_spec,
    transition_event_spec,
    webgl_context_event_spec,
)
from .blob_error_close_events import (
    Blob,
    BlobEvent,
    CloseEvent,
    Error,
    ErrorEvent,
    blob_event_spec,
    close_event_spec,
    error_event_spec,
)
from .clipboard_events import (
    ClipboardEvent,
    CopyEvent,
    CutEvent,
    PasteEvent,
    clipboard_event_spec,
    copy_event_spec,
    cut_event_spec,
    paste_event_spec,
)
from .custom_events import CustomEvent, custom_event_spec
from .fetch_form_submit_events import (
    FetchEvent,
    FormData,
    FormDataEvent,
    Request,
    SubmitEvent,
    fetch_event_spec,
    form_data_event_spec,
    submit_event_spec,
)
from .focus_events import BlurEvent, FocusEvent, FocusInEvent, blur_event_spec, focus_event_spec, focus_in_event_spec
from .gamepad_hash_popstate_storage_events import (
    Gamepad,
    GamepadEvent,
    HashChangeEvent,
    PopStateEvent,
    Storage,
    StorageEvent,
    gamepad_event_spec,
    hash_change_event_spec,
    pop_state_event_spec,
    storage_event_spec,
)
from .generic_events import (
    Event,
    ProgressEvent,
    SecurityPolicyViolationEvent,
    event_spec,
    progress_event_spec,
    security_policy_violation_event_spec,
)
from .keyboard_events import (
    BeforeInputEvent,
    CompositionEndEvent,
    CompositionEvent,
    CompositionStartEvent,
    CompositionUpdateEvent,
    InputEvent,
    KeyboardEvent,
    KeyDownEvent,
    KeyUpEvent,
    before_input_event_spec,
    composition_end_event_spec,
    composition_event_spec,
    composition_start_event_spec,
    composition_update_event_spec,
    input_event_spec,
    key_down_event_spec,
    key_up_event_spec,
    keyboard_event_spec,
)
from .mouse_events import (
    DoubleClickEvent,
    DragEndEvent,
    DragEnterEvent,
    DragEvent,
    DragLeaveEvent,
    DragOverEvent,
    DragStartEvent,
    DropEvent,
    MouseEvent,
    PointerEvent,
    WheelEvent,
    double_click_event_spec,
    drag_end_event_spec,
    drag_enter_event_spec,
    drag_event_spec,
    drag_leave_event_spec,
    drag_over_event_spec,
    drag_start_event_spec,
    drop_event_spec,
    mouse_event_spec,
    pointer_event_spec,
    wheel_event_spec,
)
from .pointer_events import (
    GotPointerCaptureEvent,
    LostPointerCaptureEvent,
    PointerCancelEvent,
    PointerDownEvent,
    PointerEnterEvent,
    PointerLeaveEvent,
    PointerMoveEvent,
    PointerOutEvent,
    PointerOverEvent,
    PointerUpEvent,
    got_pointer_capture_event_spec,
    lost_pointer_capture_event_spec,
    pointer_cancel_event_spec,
    pointer_down_event_spec,
    pointer_enter_event_spec,
    pointer_leave_event_spec,
    pointer_move_event_spec,
    pointer_out_event_spec,
    pointer_over_event_spec,
    pointer_up_event_spec,
)
from .touch_events import TouchEvent, touch_event_spec
from .ui_events import ScrollEndEvent, ScrollEvent, UIEvent, scroll_end_event_spec, scroll_event_spec, ui_event_spec
from .unload_transition_events import (
    BeforeUnloadEvent,
    PageTransitionEvent,
    before_unload_event_spec,
    page_transition_event_spec,
)

__all__ = [
    "AnimationEndEvent",
    # animation_transition_events
    "AnimationEvent",
    "AnimationIterationEvent",
    "AnimationStartEvent",
    "BeforeInputEvent",
    # unload_transition_events
    "BeforeUnloadEvent",
    # blob_error_close_events
    "Blob",
    "BlobEvent",
    "BlurEvent",
    # clipboard_events
    "ClipboardEvent",
    "CloseEvent",
    "CompositionEndEvent",
    "CompositionEvent",
    "CompositionStartEvent",
    "CompositionUpdateEvent",
    "CopyEvent",
    # custom_events
    "CustomEvent",
    "CutEvent",
    "DoubleClickEvent",
    "DragEndEvent",
    "DragEnterEvent",
    "DragEvent",
    "DragLeaveEvent",
    "DragOverEvent",
    "DragStartEvent",
    "DropEvent",
    "Error",
    "ErrorEvent",
    # generic_events
    "Event",
    "FetchEvent",
    # focus_events
    "FocusEvent",
    "FocusInEvent",
    "FormData",
    "FormDataEvent",
    # gamepad_hash_popstate_storage_events
    "Gamepad",
    "GamepadEvent",
    # pointer_events
    "GotPointerCaptureEvent",
    "HashChangeEvent",
    "InputEvent",
    "KeyDownEvent",
    "KeyUpEvent",
    # keyboard_events
    "KeyboardEvent",
    "LostPointerCaptureEvent",
    # mouse_events
    "MouseEvent",
    "PageTransitionEvent",
    "PasteEvent",
    "PointerCancelEvent",
    "PointerDownEvent",
    "PointerEnterEvent",
    "PointerEvent",
    "PointerLeaveEvent",
    "PointerMoveEvent",
    "PointerOutEvent",
    "PointerOverEvent",
    "PointerUpEvent",
    "PopStateEvent",
    "ProgressEvent",
    # fetch_form_submit_events
    "Request",
    "ScrollEndEvent",
    "ScrollEvent",
    "SecurityPolicyViolationEvent",
    "Storage",
    "StorageEvent",
    "SubmitEvent",
    # touch_events
    "TouchEvent",
    "TransitionEvent",
    # ui_events
    "UIEvent",
    "WebGLContextEvent",
    "WheelEvent",
    "animation_end_event_spec",
    "animation_event_spec",
    "animation_iteration_event_spec",
    "animation_start_event_spec",
    "before_input_event_spec",
    "before_unload_event_spec",
    "blob_event_spec",
    "blur_event_spec",
    "clipboard_event_spec",
    "close_event_spec",
    "composition_end_event_spec",
    "composition_event_spec",
    "composition_start_event_spec",
    "composition_update_event_spec",
    "copy_event_spec",
    "custom_event_spec",
    "cut_event_spec",
    "double_click_event_spec",
    "drag_end_event_spec",
    "drag_enter_event_spec",
    "drag_event_spec",
    "drag_leave_event_spec",
    "drag_over_event_spec",
    "drag_start_event_spec",
    "drop_event_spec",
    "error_event_spec",
    "event_spec",
    "fetch_event_spec",
    "focus_event_spec",
    "focus_in_event_spec",
    "form_data_event_spec",
    "gamepad_event_spec",
    "got_pointer_capture_event_spec",
    "hash_change_event_spec",
    "input_event_spec",
    "key_down_event_spec",
    "key_up_event_spec",
    "keyboard_event_spec",
    "lost_pointer_capture_event_spec",
    "mouse_event_spec",
    "page_transition_event_spec",
    "paste_event_spec",
    "pointer_cancel_event_spec",
    "pointer_down_event_spec",
    "pointer_enter_event_spec",
    "pointer_event_spec",
    "pointer_leave_event_spec",
    "pointer_move_event_spec",
    "pointer_out_event_spec",
    "pointer_over_event_spec",
    "pointer_up_event_spec",
    "pop_state_event_spec",
    "progress_event_spec",
    "scroll_end_event_spec",
    "scroll_event_spec",
    "security_policy_violation_event_spec",
    "storage_event_spec",
    "submit_event_spec",
    "touch_event_spec",
    "transition_event_spec",
    "ui_event_spec",
    "webgl_context_event_spec",
    "wheel_event_spec",
]
